apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-deployment
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: springboot-k8s-deployment
    spec:
      containers:
        - name: springboot-k8s-deployment
          image: springbootk8sdemo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
