apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
spec:
  selector:
    app: springboot-k8s-deployment

  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088

  type: NodePort